######################################################################
# Automatically generated by qmake (3.0) Tue Jun 24 14:29:11 2014
######################################################################

TEMPLATE = app
TARGET = fruit
INCLUDEPATH += .

# Input
HEADERS += animation.h fruit.h knife.h mainwindow.h
SOURCES += animation.cpp fruit.cpp knife.cpp main.cpp mainwindow.cpp
RESOURCES += fruit.qrc
QT += widgets
