#############################################################################
# Makefile for building: fruit.app/Contents/MacOS/fruit
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  fruit.pro
# Template: app
# Command: /Users/secret/Documents/workspace/qt/5.2.0/clang_64/bin/qmake -o Makefile fruit.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang -I. -I. -I../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../../workspace/qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/secret/Documents/workspace/qt/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = animation.cpp \
		fruit.cpp \
		knife.cpp \
		main.cpp \
		mainwindow.cpp qrc_fruit.cpp \
		moc_animation.cpp \
		moc_fruit.cpp \
		moc_knife.cpp \
		moc_mainwindow.cpp
OBJECTS       = animation.o \
		fruit.o \
		knife.o \
		main.o \
		mainwindow.o \
		qrc_fruit.o \
		moc_animation.o \
		moc_fruit.o \
		moc_knife.o \
		moc_mainwindow.o
DIST          = ../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		fruit.pro \
		fruit.qrc \
		fruit.pro
QMAKE_TARGET  = fruit
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = fruit.app/Contents/MacOS/fruit

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile fruit.app/Contents/PkgInfo fruit.app/Contents/Resources/empty.lproj fruit.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d fruit.app/Contents/MacOS/ || mkdir -p fruit.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fruit.pro ../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		fruit.pro \
		fruit.qrc \
		/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile fruit.pro
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/qdevice.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/device_config.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/unix.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/mac.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/macx.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/qconfig.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt_config.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_pre.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/default_post.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/warn_on.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/qt.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/resources.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/moc.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/uic.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/exceptions.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/yacc.prf:
../../../../workspace/qt/5.2.0/clang_64/mkspecs/features/lex.prf:
fruit.pro:
fruit.qrc:
/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/secret/documents/workspace/qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile fruit.pro

qmake_all: FORCE

fruit.app/Contents/PkgInfo: 
	@test -d fruit.app/Contents || mkdir -p fruit.app/Contents
	@$(DEL_FILE) fruit.app/Contents/PkgInfo
	@echo "APPL????" >fruit.app/Contents/PkgInfo
fruit.app/Contents/Resources/empty.lproj: 
	@test -d fruit.app/Contents/Resources || mkdir -p fruit.app/Contents/Resources
	@touch fruit.app/Contents/Resources/empty.lproj
	
fruit.app/Contents/Info.plist: 
	@test -d fruit.app/Contents || mkdir -p fruit.app/Contents
	@$(DEL_FILE) fruit.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,fruit,g" -e "s,@TYPEINFO@,????,g" ../../../../workspace/qt/5.2.0/clang_64/mkspecs/macx-clang/Info.plist.app >fruit.app/Contents/Info.plist
dist: 
	@test -d .tmp/fruit1.0.0 || mkdir -p .tmp/fruit1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fruit1.0.0/ && $(COPY_FILE) --parents fruit.qrc .tmp/fruit1.0.0/ && $(COPY_FILE) --parents animation.h fruit.h knife.h mainwindow.h .tmp/fruit1.0.0/ && $(COPY_FILE) --parents animation.cpp fruit.cpp knife.cpp main.cpp mainwindow.cpp .tmp/fruit1.0.0/ && (cd `dirname .tmp/fruit1.0.0` && $(TAR) fruit1.0.0.tar fruit1.0.0 && $(COMPRESS) fruit1.0.0.tar) && $(MOVE) `dirname .tmp/fruit1.0.0`/fruit1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fruit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r fruit.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_fruit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fruit.cpp
qrc_fruit.cpp: fruit.qrc \
		images/background.jpg \
		images/flash.png \
		images/fruit/peach.png \
		images/fruit/apple-1.png \
		images/fruit/strawberry-2.png \
		images/fruit/banana.png \
		images/fruit/strawberry-1.png \
		images/fruit/banana-2.png \
		images/fruit/peach-2.png \
		images/fruit/apple-2.png \
		images/fruit/banana-1.png \
		images/fruit/strawberry.png \
		images/fruit/apple.png \
		images/fruit/peach-1.png
	/Users/secret/documents/workspace/qt/5.2.0/clang_64/bin/rcc -name fruit fruit.qrc -o qrc_fruit.cpp

compiler_moc_header_make_all: moc_animation.cpp moc_fruit.cpp moc_knife.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_animation.cpp moc_fruit.cpp moc_knife.cpp moc_mainwindow.cpp
moc_animation.cpp: ../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		animation.h
	/Users/secret/documents/workspace/qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) animation.h -o moc_animation.cpp

moc_fruit.cpp: ../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsPixmapItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		animation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		fruit.h
	/Users/secret/documents/workspace/qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) fruit.h -o moc_fruit.cpp

moc_knife.cpp: ../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		knife.h
	/Users/secret/documents/workspace/qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) knife.h -o moc_knife.cpp

moc_mainwindow.cpp: ../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		mainwindow.h
	/Users/secret/documents/workspace/qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

animation.o: animation.cpp animation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o animation.cpp

fruit.o: fruit.cpp fruit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsPixmapItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		animation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsSceneHoverEvent \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fruit.o fruit.cpp

knife.o: knife.cpp knife.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsSceneMouseEvent \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRectF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knife.o knife.cpp

main.o: main.cpp fruit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsPixmapItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		animation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		knife.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		mainwindow.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsScene \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp ../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		fruit.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsPixmapItem \
		animation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPropertyAnimation \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		knife.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QQueue \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		mainwindow.h \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		../../../../workspace/qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsScene
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_fruit.o: qrc_fruit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fruit.o qrc_fruit.cpp

moc_animation.o: moc_animation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_animation.o moc_animation.cpp

moc_fruit.o: moc_fruit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fruit.o moc_fruit.cpp

moc_knife.o: moc_knife.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knife.o moc_knife.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

